export enum ModalPosition {
    CENTER = "CENTER",
    RIGHT = "RIGHT"
}

export enum ModalType {
    UPLOADPRODUCT = "UPLOADPRODUCT",
    UPDATEPRODUCT = "UPDATEPRODUCT",
    ORDERDETAILS = "ORDERDETAILS",
    CONFIRMPICKUP = "CONFIRMPICKUP",
    UPDATEBILLING = "UPDATEBILLING",
    ADDVEHICLE = "ADDVEHICLE",
    VEHICLEDETAILS = "VEHICLEDETAILS"
}